//
//  gameData.swift
//  hat
//
//  Created by Alisa Potapova on 10.12.2025.
//

/*
let section_presets_all: [SectionPreset] = [
    SectionPreset(id: 1, image: "themeImage", name: "Стартовый набор", desc: "здесь бедут боольшое описание темы Старт десь бедут боольшое описание темы Старт", questionsCount: "120", product_id: "none", state: "unlocked"),
    SectionPreset(id: 2, image: "themeImage", name: "Гарри Поттер", desc: "здесь бедут боольшое описание темы Гарри десь бедут боольшое описание темы Гарри", questionsCount: "230", product_id: "com.potapova.test", state: "locked"),
    SectionPreset(id: 3, image: "themeImage", name: "Средняя сложность", desc: "здесь бедут боольшое описание темы Средняя десь бедут боольшое описание темы Средняя", questionsCount: "187", product_id: "com.potapova.test", state: "locked"),
]
*/

let section_presets_all = [
    "ru": [
        SectionPreset(id: 1, image: "theme_1", name: "Стартовый", desc: "Стартовая подборка разных слов", wordsCount: "200"),
        SectionPreset(id: 2, image: "theme_3", name: "Все слова", desc: "Самая большая подборка слов - никаких повторов!", wordsCount: "46794"),
        SectionPreset(id: 3, image: "theme_4", name: "Легкий", desc: "Простые слова для динамичной игры", wordsCount: "3012"),
        SectionPreset(id: 4, image: "theme_5", name: "Средний", desc: "Слова среднего уровня сложности", wordsCount: "26362"),
        SectionPreset(id: 5, image: "theme_6", name: "Сложный", desc: "Самые сложные слова, фразы, термины", wordsCount: "17420"),
        SectionPreset(id: 6, image: "theme_7", name: "Детский", desc: "Играем с детьми: сказки, мультики, легкие слова", wordsCount: "310"),
        SectionPreset(id: 7, image: "theme_8", name: "Знаменитости", desc: "Артисты, политики, известные личности", wordsCount: "1743"),
        SectionPreset(id: 8, image: "theme_9", name: "Кино, Мультики", desc: "Фильмы, актеры, ведущие, мультфильмы и их герои", wordsCount: "1591"),
        SectionPreset(id: 9, image: "theme_10", name: "Тренды и бренды", desc: "Хайповые слова и всевозможные бренды", wordsCount: "689"),
        SectionPreset(id: 10, image: "theme_11", name: "Словосочетания", desc: "Фразы из нескольких слов", wordsCount: "3428"),
        SectionPreset(id: 11, image: "theme_12", name: "Спорт", desc: "Виды спорта, спортсмены, инвентарь", wordsCount: "409"),
        SectionPreset(id: 12, image: "theme_13", name: "Путешествия", desc: "Страны, города, туризм, географические названия", wordsCount: "566"),
        SectionPreset(id: 13, image: "theme_14", name: "Природа", desc: "Звери, птицы, рыбы, насекомые, погода", wordsCount: "337"),
        SectionPreset(id: 14, image: "theme_15", name: "Музыка", desc: "Песни, группы, композиторы и др.", wordsCount: "309"),
        SectionPreset(id: 15, image: "theme_16", name: "Литература", desc: "Книги и их герои, писатели и др.", wordsCount: "712"),
        SectionPreset(id: 16, image: "theme_17", name: "Искусство", desc: "Художники, стили, картины и др.", wordsCount: "331"),
        SectionPreset(id: 17, image: "theme_18", name: "Профессии", desc: "Все профессии на свете", wordsCount: "227"),
        SectionPreset(id: 18, image: "theme_19", name: "Технологии", desc: "Современные технологии и ИТ", wordsCount: "287"),
        SectionPreset(id: 19, image: "theme_20", name: "Наука", desc: "Термины, ученые, открытия", wordsCount: "622"),
        SectionPreset(id: 20, image: "theme_21", name: "Изобретения", desc: "Изобретения и изобретатели", wordsCount: "224"),
        SectionPreset(id: 21, image: "theme_22", name: "Женщины", desc: "Красота, косметика, одежда, увлечения", wordsCount: "518"),
        SectionPreset(id: 22, image: "theme_23", name: "Мужчины", desc: "Машины, компьютеры, ремонт, спорт, оружие", wordsCount: "351"),
        SectionPreset(id: 23, image: "theme_24", name: "Дом и быт", desc: "Мебель, техника, быт", wordsCount: "354"),
        SectionPreset(id: 24, image: "theme_25", name: "Школа", desc: "Уроки и канцелярия", wordsCount: "265"),
        SectionPreset(id: 25, image: "theme_26", name: "Лето", desc: "Все про приятную летнюю пору", wordsCount: "632"),
        SectionPreset(id: 26, image: "theme_27", name: "Новый год", desc: "Все про счастливый Новый год", wordsCount: "232"),
        SectionPreset(id: 27, image: "theme_28", name: "Праздники", desc: "Самые популярные праздники", wordsCount: "366"),
        SectionPreset(id: 28, image: "theme_29", name: "Хобби", desc: "Все увлечения и материалы", wordsCount: "299"),
        SectionPreset(id: 29, image: "theme_30", name: "Человек", desc: "Эмоции человека, характер и внешность", wordsCount: "418"),
        SectionPreset(id: 30, image: "theme_31", name: "Гардероб", desc: "Одежда, обувь, аксессуары", wordsCount: "663"),
        SectionPreset(id: 31, image: "theme_32", name: "Животные", desc: "Звери, птицы, рыбы", wordsCount: "150"),
        SectionPreset(id: 32, image: "theme_33", name: "Кушать подано", desc: "Блюда, ингридиенты, продукты", wordsCount: "229"),
        SectionPreset(id: 33, image: "theme_34", name: "Транспорт", desc: "Виды и названия транспорта, детали", wordsCount: "297"),
        SectionPreset(id: 34, image: "theme_35", name: "Семейный", desc: "Слова для всей семьи", wordsCount: "116"),
        SectionPreset(id: 35, image: "theme_36", name: "Космос", desc: "Планеты, звезды, техника", wordsCount: "488"),
        SectionPreset(id: 36, image: "theme_37", name: "Мифы", desc: "Греческие, римские, скандинавские мифы", wordsCount: "186"),
        SectionPreset(id: 37, image: "theme_38", name: "Гарри Поттер", desc: "Вселенная Гарри Поттера", wordsCount: "230"),
        SectionPreset(id: 38, image: "theme_39", name: "Властелин Колец", desc: "Вселенная Властелина Колец", wordsCount: "115"),
        SectionPreset(id: 39, image: "theme_40", name: "Marvel", desc: "Вселенная Marvel", wordsCount: "249"),
    ],
    "en": [
        SectionPreset(id: 1, image: "theme_1", name: "Start", desc: "Start set of different words", wordsCount: "200"),
        SectionPreset(id: 2, image: "theme_3", name: "All words", desc: "The largest set of unique words", wordsCount: "41280"),
        SectionPreset(id: 3, image: "theme_4", name: "Easy", desc: "Simple words for a dynamic game", wordsCount: "20948"),
        SectionPreset(id: 4, image: "theme_5", name: "Medium", desc: "Medium difficulty words", wordsCount: "13369"),
        SectionPreset(id: 5, image: "theme_6", name: "Hard", desc: "The most difficult words, phrases, terms", wordsCount: "5322"),
        SectionPreset(id: 6, image: "theme_7", name: "Kids", desc: "Play with children - fairy tales, cartoons, simple words", wordsCount: "225"),
        SectionPreset(id: 7, image: "theme_8", name: "Celebrities", desc: "Artists, politicians, models a.o.", wordsCount: "1233"),
        SectionPreset(id: 8, image: "theme_9", name: "Movies & Cartoons", desc: "Films, actors, TV shows, cartoons, characters a.o.", wordsCount: "1134"),
        SectionPreset(id: 9, image: "theme_10", name: "Trends & Brands", desc: "Hype words and all kinds of brands", wordsCount: "580"),
        SectionPreset(id: 10, image: "theme_11", name: "Phrases", desc: "Multi-word phrases", wordsCount: "1536"),
        SectionPreset(id: 11, image: "theme_12", name: "Sport", desc: "Kinds of sport, sportsmen, equipment", wordsCount: "390"),
        SectionPreset(id: 12, image: "theme_13", name: "Travel", desc: "Countries, cities, tourism, place names", wordsCount: "555"),
        SectionPreset(id: 13, image: "theme_14", name: "Nature", desc: "Animals, weather, environment a.o.", wordsCount: "311"),
        SectionPreset(id: 14, image: "theme_15", name: "Music", desc: "Songs, music bands, composers a.o.", wordsCount: "148"),
        SectionPreset(id: 15, image: "theme_16", name: "Literature", desc: "Books and their characters, writers a.o.", wordsCount: "586"),
        SectionPreset(id: 16, image: "theme_17", name: "Art", desc: "Artists, styles, pictures a.o.", wordsCount: "306"),
        SectionPreset(id: 17, image: "theme_18", name: "Professions", desc: "All professions in the world", wordsCount: "234"),
        SectionPreset(id: 18, image: "theme_19", name: "Technologies", desc: "Modern technologies and IT", wordsCount: "282"),
        SectionPreset(id: 19, image: "theme_20", name: "Science", desc: "Terms, scientists, discoveries", wordsCount: "441"),
        SectionPreset(id: 20, image: "theme_21", name: "Inventions", desc: "Inventors and their inventions", wordsCount: "213"),
        SectionPreset(id: 21, image: "theme_22", name: "Women", desc: "Beauty, cosmetics, clothes, hobbies", wordsCount: "488"),
        SectionPreset(id: 22, image: "theme_23", name: "Men", desc: "Cars, computers, sports, weapons", wordsCount: "346"),
        SectionPreset(id: 23, image: "theme_24", name: "House", desc: "Furniture and household appliances", wordsCount: "388"),
        SectionPreset(id: 24, image: "theme_25", name: "School", desc: "Lessons and stationery", wordsCount: "258"),
        SectionPreset(id: 25, image: "theme_26", name: "Summer", desc: "All about a wonderful summertime", wordsCount: "569"),
        SectionPreset(id: 26, image: "theme_27", name: "New Year", desc: "All about Happy New Year", wordsCount: "208"),
        SectionPreset(id: 27, image: "theme_28", name: "Holidays", desc: "The most popular holidays in the world", wordsCount: "305"),
        SectionPreset(id: 28, image: "theme_29", name: "Hobby", desc: "Hobbies, materials and tools", wordsCount: "294"),
        SectionPreset(id: 29, image: "theme_30", name: "Person", desc: "Human emotions, character and appearance", wordsCount: "385"),
        SectionPreset(id: 30, image: "theme_31", name: "Clothes", desc: "Clothes, shoes, accessories", wordsCount: "584"),
        SectionPreset(id: 31, image: "theme_32", name: "Animals", desc: "Animals, birds, fish", wordsCount: "149"),
        SectionPreset(id: 32, image: "theme_33", name: "Food", desc: "Dishes, ingredients, products", wordsCount: "196"),
        SectionPreset(id: 33, image: "theme_34", name: "Transport", desc: "Types and names of transport, machine parts", wordsCount: "280"),
        SectionPreset(id: 34, image: "theme_35", name: "Family", desc: "Words for the whole family", wordsCount: "92"),
        SectionPreset(id: 35, image: "theme_36", name: "Space", desc: "Planets, stars, astronomy", wordsCount: "148"),
        SectionPreset(id: 36, image: "theme_37", name: "Myths", desc: "Greek, Roman, Scandinavian myths", wordsCount: "186"),
        SectionPreset(id: 37, image: "theme_38", name: "Harry Potter", desc: "Universe of Harry Potter", wordsCount: "230"),
        SectionPreset(id: 38, image: "theme_39", name: "Lord of the Rings", desc: "Lord of the Rings Universe", wordsCount: "114"),
        SectionPreset(id: 39, image: "theme_40", name: "Marvel", desc: "Marvel Universe", wordsCount: "248"),
    ]
]

let tasks_all = [
    "ru": [
        "Встав на табуретку",
        "Танцуя танго с игроком того же пола",
        "Изображая собаку",
        "Позируя как бодибилдер",
        "Целуя одного из игроков в руку",
        "Изображая маньяка",
        "Изображая злодея из фильмов",
        "Изображая экстаз",
        "Изображая священника",
        "Как оперный певец",
        "Целуя какой-нибудь предмет",
        "Поглаживая себя по голове",
        "Поглаживая какой-нибудь предмет",
        "Держа любого игрока за руки и кружась",
        "Кружась как балерина",
        "Обнимая двух игроков как братанов",
        "Ходи в стиле краба",
        "Зевая",
        "Прыгая как лягушка",
        "Рыгая",
        "Щелкая пальцами обеих рук",
        "Танцуя тверк",
        "Крутя попой",
        "Ходя как модель по подиуму",
        "Танцуя Брейк-данс",
        "Делая массаж любому игроку",
        "Прыгая на одной ноге",
        "Поглаживая себя по плечам",
        "Делая себе усы пальцами рук",
        "Пропевая словно песню",
        "Получая поджопник от всех игроков по очереди",
        "Танцуя танец живота",
        "С максимально широкой улыбкой",
        "Голосом Путина",
        "Изображая любого из игроков",
        "Делая вид, что чистишь зубы",
        "Делая вид, что красишь ресницы",
        "Бегая с поднятыми вверх руками",
        "Шепотом, поглаживая стену",
        "Делая отжимания",
        "Крася губы помадой/блеском",
        "Делая себе массаж головы",
        "Показывая свои бицепсы",
        "Целуя себя в бицепс",
        "Накручивая волосы на палец",
        "делая ласточку",
        "сидя на полу и раскачиваясь",
        "стоя спиной к другим игрокам",
        "прыгая на одной ноге",
        "хлопая себя по голове",
        "хлопая в ладоши",
        "делать приседания",
        "бегая на месте",
        "тряся телефоном",
        "поглаживая другого игрока",
        "танцуя ламбаду",
        "исполняя танец маленьких утят",
        "танцуя лезгинку",
        "стоя в позе йога",
        "подняв руки вверх",
        "сидя в позе лотоса",
        "стоя на четвереньках",
        "стоя в позе звезды",
        "качая головой влево-вправо",
        "кивая головой",
        "пожимая плечами",
        "делая вид, что куришь",
        "накручивая волосы на палец",
        "держа пальцы у висков",
        "в позе собачки-попрошайки",
        "делая фейс-палм",
        "в сексуальной позе",
        "вкручивая руками лампочку",
        "делая вид, что стреляешь",
        "отжимаясь",
        "топая ногами",
        "ходить на носочках",
        "ходить на пяточках",
        "кружась",
        "сидя на корточках",
        "ходить гуськом",
        "делая руками волну",
        "держа телефон у лба",
        "подняв руки вверх",
        "встав на мостик",
        "прыгая как зайчик",
        "хмуря брови",
        "делая руками маску бэтмена",
        "шевеля руками свои уши",
        "делая нос пятачком",
        "схватившись за голову",
        "делая зарядку",
        "испуганно",
        "истерично",
        "радостно",
        "со злостью",
        "смущенно",
        "в шоке",
        "плача",
        "уныло",
        "агрессивно",
        "занудно",
        "азартно",
        "сходя с ума",
        "напряжено",
        "флиртуя",
        "с озорством",
        "жалостливо",
        "безразлично",
        "в экстазе",
        "устало",
        "увлеченно",
        "нежно",
        "умиротворенно",
        "раздраженно",
        "обиженно",
        "лая по-собачьи",
        "хрюкая",
        "страдая",
    ],
    "en": [
        "making a swallow",
        "sitting on the floor and swaying",
        "standing back to other players",
        "jumping on one leg",
        "slapping the head",
        "clapping",
        "do squats",
        "running",
        "shaking the phone",
        "stroking another player",
        "dancing",
        "standing in a yoga pose",
        "raising arms up",
        "sitting in the lotus pose",
        "standing on all fours",
        "standing in a star pose",
        "shaking your head left-right",
        "nodding the head",
        "shrug",
        "pretending to smoke",
        "twirling hair on your finger",
        "holding fingers at the temples",
        "in the pose of a dog-beggar",
        "making face-palm",
        "in a sexy pose",
        "screwing up the light bulb",
        "pretending to shoot",
        "wringing",
        "stamping feet",
        "to walk on socks",
        "walking on the heels",
        "circling",
        "squatting",
        "one-handed",
        "making a wave with your hands",
        "holding the phone at the forehead",
        "raising arms up",
        "standing on the bridge",
        "jumping like a bunny",
        "frown",
        "making batman mask",
        "wiggling his ears",
        "clutching the head",
        "doing exercises",
        "scared",
        "hysterical",
        "joyfully",
        "with anger",
        "embarrassed",
        "shocked",
        "crying",
        "sad",
        "aggressively",
        "boring",
        "recklessly",
        "going crazy",
        "tense",
        "flirting",
        "with mischief",
        "pitifully",
        "in ecstasy",
        "wearily",
        "enthusiastically",
        "gently",
        "peacefully",
        "annoyed",
        "offended",
        "dog barking",
        "grunt"
    ]
]

let teamPlayersNames_all = [
    "ru": [
        "Суккуленты",
        "Сборная Ашота",
        "Ёжики в тумане",
        "Бегемоты",
        "Палата №6",
        "Овощи",
        "Фрукты",
        "15 см",
        "Интеграл",
        "Ракеты",
        "Торнадо",
        "Динамит",
        "Гвозди",
        "Бригада",
        "Одуванчики",
        "Банда",
        "Мамонты",
        "Перцы",
        "Белки",
        "Стрелки",
        "Пингвины",
        "Медведи",
        "Шнурки",
        "Черепашки",
        "Тапки",
        "Амеба",
        "Барсуки",
        "50 оттенков проигрыша",
        "Мудрые королевы",
        "Космические Богини",
        "Бывшие",
        "Яхонты",
        "Офисные феи",
        "Воображаемые друзья",
        "Суперпчелки",
        "Обаяшечки",
        "Антидиета",
        "Гламурные чиксы",
        "Незабудки",
        "Баловницы",
        "Милашки",
        "Стройные ножки",
        "Торнадо",
        "Пупсики",
        "Звезды Голливуда",
        "Стиляги",
        "Розовые пантеры",
        "Кошечки",
        "Конфетки",
        "Девы",
        "Халки",
        "Силачи",
        "Боксеры",
        "Бодибилдеры",
        "Качки",
        "Крепыши",
        "Легион",
        "Босяки",
        "Элита",
        "Отступники",
        "Боги Олимпа",
        "Киборги",
        "Снайперы",
        "Маги",
        "Спартанцы",
        "Пельмешки",
        "Армия божьих коровок",
        "Кринжовые",
        "Сокрушители времени",
        "Зомбаки",
        "Трансформеры",
        "Египетская сила",
        "Рептилоиды",
        "Колесо фортуны",
        "Интеллектуалы",
        "Боги знаний",
        "Антиматерия",
        "Теория большого взрыва",
        "Штормовое предупреждение",
        "Сиреневый туман",
        "Полярные медведи",
        "Сверхзвуковые чайки",
        "Канарейки",
        "Бригада",
        "Голубчики",
        "Колбаса из овса",
        "Хамон по акции",
        "Анонимусы",
        "Нежнейшее повидло",
        "Запахло жареным",
        "Ладушки-Оладушки",
        "Лечу куда хочу",
        "Антициклон",
        "Истребители пиццы",
        "Шашлычники",
        "Котелок-то не варит",
        "Эверест",
        "Стражи Галактики",
        "Черепашки ниндзя",
        "Мстители",
        "Лига Справедливости",
        "Витязи",
        "Мушкетеры",
        "Ниндзи бадминтона",
        "Лунтики",
        "Фиксики",
        "Велоцерапторы",
        "Кунг-фу панды",
        "Катапульта"
    ],
    "en": [
        "Kung Fu Pandas",
        "Velociraptors",
        "Zombies",
        "Antimatter",
        "The Big Bang Theory",
        "Ladybugs army",
        "Cyborgs",
        "Snipers",
        "Bodybuilders",
        "Boxers",
        "Strongmen",
        "Hulks",
        "Pink Panthers",
        "Hurricane",
        "Slender legs",
        "Imaginary Friends",
        "Bombs",
        "Cockroaches",
        "Ducks",
        "Antagonists",
        "Turkeys",
        "Cowboys",
        "Earworms",
        "Second Place",
        "TikTok on the Clock",
        "Busy Bugs",
        "Tigers",
        "Sweetheart",
        "Kryptonite",
        "Virtuosos",
        "Antiheroes",
        "Gorgeous",
        "Dumpling",
        "Sunshine",
        "Teddy Bears",
        "Captain",
        "Bubba",
        "Chefs",
        "Coaches",
        "Seniors",
        "Chipmunks",
        "Oldie",
        "Perfect",
        "Lady Killers",
        "Baby Faces",
        "Big Bros",
        "Amigos",
        "Vikings",
        "Ninjas",
        "CatDogs",
        "Queens",
        "Crazy",
        "Angels"
    ]
]

let singlePlayersNames_all = [
    "ru": [
        "Суккулент",
        "Ашот",
        "Ёжик в тумане",
        "Бегемот",
        "Палата №6",
        "Овощ",
        "Фрукт",
        "15 см",
        "Интеграл",
        "Ракета",
        "Пушка",
        "Бомба",
        "Торнадо",
        "Динамит",
        "Гвоздь",
        "Бригада",
        "Одуванчик",
        "Банда",
        "Мамонт",
        "Перец",
        "Белка",
        "Стрелка",
        "Пингвин",
        "Медведь",
        "Шнурок",
        "Черепашка",
        "Тапок",
        "Амеба",
        "Барсук",
        "50 оттенков проигрыша",
        "Мудрая королева",
        "Космическая Богиня",
        "Бывшая",
        "Яхонт",
        "Офисная фея",
        "Воображаемый друг",
        "Суперпчелка",
        "Обаяшечка",
        "Антидиета",
        "Гламурная чика",
        "Незабудка",
        "Баловница",
        "Милашка",
        "Стройные ножки",
        "Торнадо",
        "Пупсик",
        "Звезда Голливуда",
        "Стиляга",
        "Розовая пантера",
        "Кошечка",
        "Конфетка",
        "Дева",
        "Халк",
        "Силач",
        "Боксер",
        "Бодибилдер",
        "Качок",
        "Крепыш",
        "Легион",
        "Босяк",
        "Элита",
        "Отступник",
        "Бог Олимпа",
        "Киборг",
        "Снайпер",
        "Маг",
        "Спартанец",
        "Пельмешка",
        "Армия божьих коровок",
        "Кринжовый",
        "Сокрушитель времени",
        "Зомбак",
        "Трансформер",
        "Египетская сила",
        "Рептилоид",
        "Колесо фортуны",
        "Интеллектуал",
        "Бог знаний",
        "Антиматерия",
        "Теория большого взрыва",
        "Штормовое предупреждение",
        "Сиреневый туман",
        "Полярный медведь",
        "Сверхзвуковая чайка",
        "Канарейка",
        "Бригада",
        "Голубчик",
        "Колбаса из овса",
        "Хамон по акции",
        "Анонимус",
        "Нежнейшее повидло",
        "Запахло жареным",
        "Ладушки-Оладушки",
        "Лечу куда хочу",
        "Антициклон",
        "Истребитель пиццы",
        "Шашлычник",
        "Котелок-то не варит",
        "Эверест",
        "Страж Галактики",
        "Черепашка ниндзя",
        "Мститель",
        "Лига Справедливости",
        "Витязь",
        "Мушкетер",
        "Ниндзя бадминтона",
        "Лунтик",
        "Фиксик",
        "Велоцераптор",
        "Кунг-фу панда",
        "Катапульта"
    ],
    "en": [
        "Kung Fu Panda",
        "Velociraptor",
        "Zombie",
        "Antimatter",
        "The Big Bang Theory",
        "Ladybugs army",
        "Cyborg",
        "Sniper",
        "Bodybuilder",
        "Boxer",
        "Strongman",
        "Hulk",
        "Pink Panther",
        "Hurricane",
        "Slender legs",
        "Imaginary friend",
        "Bomb",
        "Cockroach",
        "Duck",
        "Antagonist",
        "Turkey",
        "Cowboy",
        "Earworm",
        "Second Place",
        "TikTok on the Clock",
        "Busy Bug",
        "Tiger",
        "Sweetheart",
        "Kryptonite",
        "Virtuoso",
        "Antihero",
        "Gorgeous",
        "Dumpling",
        "Sunshine",
        "Teddy Bear",
        "Captain",
        "Bubba",
        "Chief",
        "Coach",
        "Senior",
        "Chipmunk",
        "Oldie",
        "Mr. Perfect",
        "Lady Killer",
        "Baby Face",
        "Big Bro",
        "Amigo",
        "Viking",
        "Ninja",
        "CatDog",
        "Queen",
        "Crazy"
    ]
    
]

let player_presets_all = [
    "ru": [
        PlayerPreset(id: 1, name: "Перцы"),
        PlayerPreset(id: 2, name: "Одуванчики"),
    ],
    "en": [
        PlayerPreset(id: 1, name: "Peppers"),
        PlayerPreset(id: 2, name: "Lions"),
    ]
]



let wordsCountArray = ["30", "50", "70", "90", "100"]
let roundTimes = ["30", "60", "90", "120", "130"]
let roundNames = ["Словами", "Жестами", "Одним словом", "Рисунком"]
let roundDescs = ["объясняйте слова\nдругими словами,\nне используя\nоднокоренные", "объясняйте слова\nжестами,\nне говоря ни слова", "объясняйте слова\nпроизнеся\nвсего одно слово", "объясняйте слова\nс помощью рисунков,\nиспользуя ручку и бумагу"]



let teamPlayersNames = teamPlayersNames_all[cur_lang] ?? []
let singlePlayersNames = singlePlayersNames_all[cur_lang] ?? []
let tasks = tasks_all[cur_lang] ?? []
let sectionPresets = section_presets_all[cur_lang] ?? []
let playerPresets = player_presets_all[cur_lang] ?? []
var all_themes = Loader.loadJson(fileName: "all_themes_\(cur_lang)", fileType: "json") as? [String: [Int]] ?? [String: [Int]]()
var all_words = Loader.loadJson(fileName: "all_words_\(cur_lang)", fileType: "json") as? [String] ?? [String]()

var defaultSelectedSectionsIds = [1]
var defaultSections = ["first"]
let defaultRoundTypes = "[\"1\",\"1\",\"1\",\"0\"]"
let defaultGameType = 0
let defaultRoundTime = 60
let defaultWordsCount = 30
let defaultSelectOwnRoundTime = false
let defaultSelectOwnWordsCount = false
let defaultMoveTime = false
let defaultExtraTime = false
let defaultCommonLastWord = false
let defaultGameWithTasks = true
let defaultMinusForMistake = false
let defaultPlusForSpeed = false
let defaultGameSounds = true
let defaultRoundStartsFirstPlayer = false

let minWordsCount = 5
let maxWordsCount = 150
let stepWordsCount = 1

let minRoundTime = 10 // для теста удалить - изменить на let minRoundTime = 10
let maxRoundTime = 300
let stepRoundTime = 1





