let searchTitle = lang_scheme[cur_lang]?["search"] as? String ?? ""
let cancelTitle = lang_scheme[cur_lang]?["сancel"] as? String ?? ""
let backTitle = lang_scheme[cur_lang]?["back"] as? String ?? ""
let yesTitle = lang_scheme[cur_lang]?["yes"] as? String ?? ""
let noTitle = lang_scheme[cur_lang]?["no"] as? String ?? ""
let okTitle = lang_scheme[cur_lang]?["ok"] as? String ?? ""
let editTitle = lang_scheme[cur_lang]?["edit"] as? String ?? ""
let deleteTitle = lang_scheme[cur_lang]?["delete"] as? String ?? ""
let deleteAllTitle = lang_scheme[cur_lang]?["deleteAll"] as? String ?? ""
let deleteSelectedTitle = lang_scheme[cur_lang]?["deleteSelected"] as? String ?? ""
let selectTitle = lang_scheme[cur_lang]?["select"] as? String ?? ""
let unselectTitle = lang_scheme[cur_lang]?["unselect"] as? String ?? ""
let selectAllTitle = lang_scheme[cur_lang]?["selectAll"] as? String ?? ""
let unselectAllTitle = lang_scheme[cur_lang]?["unselectAll"] as? String ?? ""
let saveTitle = lang_scheme[cur_lang]?["save"] as? String ?? ""
let addTitle = lang_scheme[cur_lang]?["add"] as? String ?? ""
let addPlusTitle = lang_scheme[cur_lang]?["addPlus"] as? String ?? ""
let addToFavoritesTitle = lang_scheme[cur_lang]?["addToFavorites"] as? String ?? ""
let deleteFromFavoritesTitle = lang_scheme[cur_lang]?["deleteFromFavorites"] as? String ?? ""
let contextActionsTitle = lang_scheme[cur_lang]?["contextActions"] as? String ?? ""
let sortAscendingTitle = lang_scheme[cur_lang]?["sortAscending"] as? String ?? ""
let sortDescendingTitle = lang_scheme[cur_lang]?["sortDescending"] as? String ?? ""
let sortAscendingSegmentTitle = lang_scheme[cur_lang]?["sortAscendingSegment"] as? String ?? ""
let sortDescendingSegmentTitle = lang_scheme[cur_lang]?["sortDescendingSegment"] as? String ?? ""
let restorePurchasesTitle = lang_scheme[cur_lang]?["restorePurchasesTitle"] as? String ?? ""
let restorePurchasesMessage = lang_scheme[cur_lang]?["restorePurchasesMessage"] as? String ?? ""
let completePurchasesTitle = lang_scheme[cur_lang]?["completePurchasesTitle"] as? String ?? ""
let completePurchasesMessage = lang_scheme[cur_lang]?["completePurchasesMessage"] as? String ?? ""
let completeManyPurchasesTitle = lang_scheme[cur_lang]?["completeManyPurchasesTitle"] as? String ?? ""
let completeManyPurchasesMessage = lang_scheme[cur_lang]?["completeManyPurchasesMessage"] as? String ?? ""
let restoringMessage = lang_scheme[cur_lang]?["restoringMessage"] as? String ?? ""
let loadingMessage = lang_scheme[cur_lang]?["loadingMessage"] as? String ?? ""
let errorTitle = lang_scheme[cur_lang]?["errorTitle"] as? String ?? ""
let errorMessage = lang_scheme[cur_lang]?["errorMessage"] as? String ?? ""


let lang_scheme = [
    "ru": [
        
        "notEnoughWordsAlertTitle": "Недостаточно слов для игры",
        "notEnoughWordsAlertMessage": "Вы выбрали категории, в которых суммарно слов меньше, чем задано в настройках игры. Сейчас в настройках выбрано SETTINGS_WORDS_COUNT слов в игре, а в категориях суммарно GAME_WORDS_COUNT слов. Чтобы начать новую игру, измените выбранные категории, либо поменяйте количество слов в настройках игры.",
        
        
        "resultsVCTitle": "Результат",
        "sectionsVCTitle": "Категории",
        "settingsVCTitle": "Настройки",
        "rulesVCTitle": "Правила",
        
        
        //own words
        "OwnwordTableViewCellTitle": "OwnwordTableViewCell",
        "ownwordsVCTitle": "Свои слова",
        "addOrEditOwnwordVCTitle": "Добавить новое слово",
        "alertAddOwnwordTitle": "Добавить новое слово",
        "alertAddOwnwordMessage": "Введите новое слово",
        "alertEditOwnwordTitle": "Изменить слово",
        "alertEditOwnwordMessage": "Введите новое слово. Старое слово: ",
        "alertMaxOwnwordsCountTitle": "Нельзя добавить слово",
        "alertMaxOwnwordsCountMessage": "Количество слов не должно быть больше maximumCount",
        "alertMinOwnwordsCountTitle": "Нельзя удалить слово",
        "alertMinOwnwordsCountMessage": "Количество слов не должно быть меньше minimumCount",
        "alertDeleteOwnwordTitle": "Удалить слово",
        "alertDeleteOwnwordMessage": "Точно удаляем слово? Данное действие нельзя будет отменить",
        "alertDeleteSelectedOwnwordsTitle": "Удалить выбранные слова",
        "alertDeleteSelectedOwnwordsMessage": "Точно удаляем выбранные слова? Данное действие нельзя будет отменить",
        "alertDeleteAllOwnwordsTitle": "Удалить все слова",
        "alertDeleteAllOwnwordsMessage": "Точно удаляем все слова? Данное действие нельзя будет отменить",
        
        //categories
        "SectionTableViewCellTitle": "SectionTableViewCell",
        "sections2VCTitle": "Категории",
        "addOrEditSectionVCTitle": "Добавить новую категорию",
        "alertAddSectionTitle": "Добавить новую категорию",
        "alertAddSectionMessage": "Введите название категории",
        "alertEditSectionTitle": "Изменить категорию",
        "alertEditSectionMessage": "Введите новую категорию. Старое название: ",
        "alertMaxSectionsCountTitle": "Нельзя добавить категорию",
        "alertMaxSectionsCountMessage": "Количество категорий не должно быть больше maximumCount",
        "alertMinSectionsCountTitle": "Нельзя удалить категорию",
        "alertMinSectionsCountMessage": "Количество категорий не должно быть меньше minimumCount",
        "alertDeleteSectionTitle": "Удалить категорию",
        "alertDeleteSectionMessage": "Точно удаляем категорию? Данное действие нельзя будет отменить",
        "alertDeleteSelectedSectionsTitle": "Удалить выбранные категории",
        "alertDeleteSelectedSectionsMessage": "Точно удаляем выбранные категории? Данное действие нельзя будет отменить",
        "alertDeleteAllSectionsTitle": "Удалить все категории",
        "alertDeleteAllSectionsMessage": "Точно удаляем все категории? Данное действие нельзя будет отменить",
        
        //players
        "playersVCTitle": "Игроки",
        "alertAddPlayerTitle": "Добавить нового игрока",
        "alertAddPlayerMessage": "Введите новое имя игрока",
        "alertEditPlayerTitle": "Изменить игрока",
        "alertEditPlayerMessage": "Введите новое имя игрока. Старое имя: ",
        "alertMaxPlaayersCountTitle": "Нельзя добавить игрока",
        "alertMaxPlayersCountMessage": "Количество игроков не должно быть больше maximumCount",
        "alertMinPlayersCountTitle": "Нельзя удалить игроков",
        "alertMinPlayersCountMessage": "Количество игроков не должно быть меньше minimumCount",
        "alertDeletePlayerTitle": "Удалить игрока",
        "alertDeleteSelectedPlayersTitle": "Удалить выбранных игроков",
        "alertDeleteAllPlayersTitle": "Удалить всех игроков",
        "alertDeletePlayerMessage": "Точно удаляем игрока? Данное действие нельзя будет отменить",
        "alertDeleteSelectedPlayersMessage": "Точно удаляем выбранных игроков? Данное действие нельзя будет отменить",
        "alertDeleteAllPlayersMessage": "Точно удаляем всех игроков? Данное действие нельзя будет отменить",
        "alertDeleteAllPlayersAdditionalMessage": ". Минимальное количество игроков: PLAYERS_COUNT. Поэтому будут удалены все игроки, кроме первых PLAYERS_COUNT игроков.",
        
        "parentControl": "СПРОСИ РОДИТЕЛЕЙ",
        "guessedAction": "Угадано",
        "notguessedAction": "Неугадано",
        "InsectCollectionViewCellTitle": "InsectCollectionViewCell",
        "insectsVCTitle": "insectsVC",
        "addOrEditInsectVCTitle": "Добавить нового насекомого",
        "alertAddInsectTitle": "Добавить нового насекомого",
        "alertAddInsectMessage": "Введите новое имя насекомого",
        "alertEditInsectTitle": "Изменить насекомого",
        "alertEditInsectMessage": "Введите новое имя насекомого. Старое имя: ",
        "alertMaxInsectsCountTitle": "Нельзя добавить насекомого",
        "alertMaxInsectsCountMessage": "Количество насекомых не должно быть больше maximumCount",
        "alertMinInsectsCountTitle": "Нельзя удалить насекомых",
        "alertMinInsectsCountMessage": "Количество насекомых не должно быть меньше minimumCount",
        "alertDeleteInsectTitle": "Удалить насекомого",
        "alertDeleteInsectMessage": "Точно удаляем насекомого? Данное действие нельзя будет отменить",
        "alertDeleteSelectedInsectsTitle": "Удалить выбранных насекомых",
        "alertDeleteSelectedInsectsMessage": "Точно удаляем выбранных насекомых? Данное действие нельзя будет отменить",
        "alertDeleteAllInsectsTitle": "Удалить всех насекомых",
        "alertDeleteAllInsectsMessage": "Точно удаляем всех насекомых? Данное действие нельзя будет отменить",
        // purcahses
        "restorePurchasesTitle": "Восстановление покупок",
        "restorePurchasesMessage": "Покупки успешно восстановлены",
        "completePurchasesTitle": "Покупка полной версии",
        "completePurchasesMessage": "Покупка совершена успешно. Полная версия открыта.",
        "completeManyPurchasesTitle": "Покупка",
        "completeManyPurchasesMessage": "Покупка совершена успешно",
        "restoringMessage": "Идет процесс восстановления покупок",
        "loadingMessage": "Загрузка",
        "errorTitle": "Произошла ошибка",
        "errorMessage": "Не удалось выполнить операцию. Проверьте соединение с интернетом и повторите попытку",
        //birds
        "all birds": "Все птицы",
        "own birds": "Мои птицы",
        "BirdTableViewCellTitle": "BirdTableViewCell",
        "birds2VCTitle": "birds2VC",
        "addOrEditBirdVCTitle": "Добавить новую птицу",
        "alertAddBirdTitle": "Добавить новую птицу",
        "alertAddBirdMessage": "Введите новое имя птицу",
        "alertEditBirdTitle": "Изменить птицу",
        "alertEditBirdMessage": "Введите новое имя птицу. Старое имя: ",
        "alertMaxBirdsCountTitle": "Нельзя добавить птицу",
        "alertMaxBirdsCountMessage": "Количество птиц не должно быть больше maximumCount",
        "alertMinBirdsCountTitle": "Нельзя удалить птиц",
        "alertMinBirdsCountMessage": "Количество птиц не должно быть меньше minimumCount",
        "alertDeleteBirdTitle": "Удалить птицу",
        "alertDeleteBirdMessage": "Точно удаляем птицу? Данное действие нельзя будет отменить",
        "alertDeleteSelectedBirdsTitle": "Удалить выбранных птиц",
        "alertDeleteSelectedBirdsMessage": "Точно удаляем выбранных птиц? Данное действие нельзя будет отменить",
        "alertDeleteAllBirdsTitle": "Удалить всех птиц",
        "alertDeleteAllBirdsMessage": "Точно удаляем всех птиц? Данное действие нельзя будет отменить",
        
        "playersCountNameLabel": "Команд",
        "roundsCountNameLabel": "Раундов",
        "soundsOnNameLabel": "Звуки",
        "gameModesNameLabel": "Режимы",
        "playersButton": "Игроки",
        "playButton": "Играть",
        "titleLabel": "Текст лейбла",
        "item_1": "item_1",
        "item_2": "item_2",
        //names
        "namesVCTitle": "Имена",
        "alertAddNameTitle": "Добавить новое имя",
        "alertAddNameMessage": "Введите новое имя",
        "alertEditNameTitle": "Изменить имя",
        "alertEditNameMessage": "Введите новое имя. Старое имя: ",
        "alertMaxNamesCountTitle": "Нельзя добавить имя",
        "alertMaxNamesCountMessage": "Количество имен не должно быть больше maximumCount",
        "alertMinNamesCountTitle": "Нельзя удалить имя",
        "alertMinNamesCountMessage": "Количество имен не должно быть меньше minimumCount",
        "alertDeleteNameTitle": "Удалить имя",
        "alertDeleteSelectedNamesTitle": "Удалить выбранные имена",
        "alertDeleteAllNamesTitle": "Удалить все имена",
        "alertDeleteNameMessage": "Точно удаляем имя? Данное действие нельзя будет отменить",
        "alertDeleteSelectedNamesMessage": "Точно удаляем выбранные имена? Данное действие нельзя будет отменить",
        "alertDeleteAllNamesMessage": "Точно удаляем все имена? Данное действие нельзя будет отменить",
        //clients
        "clientsVCTitle": "Клиенты",
        "alertAddClientTitle": "Добавить нового клиента",
        "alertAddClientMessage": "Введите новое имя клиента",
        "alertEditClientTitle": "Изменить клиента",
        "alertEditClientMessage": "Введите новое имя клиента. Старое имя: ",
        "alertMaxClientsCountTitle": "Нельзя добавить клиента",
        "alertMaxClientsCountMessage": "Количество клиентов не должно быть больше maximumCount",
        "alertMinClientsCountTitle": "Нельзя удалить клиентов",
        "alertMinClientsCountMessage": "Количество клиентов не должно быть меньше minimumCount",
        "alertDeleteClientTitle": "Удалить клиента",
        "alertDeleteSelectedClientsTitle": "Удалить выбранных клиентов",
        "alertDeleteAllClientsTitle": "Удалить всех клиентов",
        "alertDeleteClientMessage": "Точно удаляем клиента? Данное действие нельзя будет отменить",
        "alertDeleteSelectedClientsMessage": "Точно удаляем выбранных клиентов? Данное действие нельзя будет отменить",
        "alertDeleteAllClientsMessage": "Точно удаляем всех клиентов? Данное действие нельзя будет отменить",
        //fruits
        "fruitsVCTitle": "Фрукты",
        "alertAddFruitTitle": "Добавление фрукта",
        "alertAddFruitMessage": "Введите новое название фрукта",
        "alertEditFruitTitle": "Изменение фрукта",
        "alertEditFruitMessage": "Введите новое название фрукта. Старое название: ",
        "alertMaxFruitsCountTitle": "Нельзя добавить фрукт",
        "alertMaxFruitsCountMessage": "Количество фруктов не должно быть больше maximumCount",
        "alertMinFruitsCountTitle": "Нельзя удалить фрукты",
        "alertMinFruitsCountMessage": "Количество фруктов не должно быть меньше minimumCount",
        //all
         "lettersVCNavigationBarTitle": "lettersVC",
        "ownTheme": "Своя категория",
        "alertIncorrectSymbolsCountTitle": "Некорректное число символов",
        "alertIncorrectSymbolsCountMessage": "currentTitle должно содержать от minimumSymbolsCount до maximumSymbolsCount символов",
        "alertIncorrectNameTitle": "Некорректное currentTitle",
        "alertIncorrectNameMessage": "Такое currentTitle уже есть. Введите другое.",
        "alertIncorrectSymbolsTitle": "Некорректные символы",
        "alertIncorrectSymbolsMessage": "Нельзя использовать символы: incorrectSymblosString",
        "lettersVCTitle": "Буквы",
        "animalsVCTitle": "Животные",
        "commandsTitle": "КОМАНДЫ",
        "gameTypeLabelLabelName": " игра",
        "mailSubject": "Вопросы и предложения по игре",
        "mailMessage": "Напишите здесь свой вопрос",
        "newGameButtonName": "Новая игра",
        "continueButtonName": "Продолжить",
        "newGameAlertTitle": "Начать новую игру?",
        "newGameAlertMessage": "Все результаты текущей игры будут удалены",
        "сancel": "Отмена",
        "yes": "Да",
        "no": "Нет",
        "ok": "OK",
        "edit": "Изменить",
        "delete": "Удалить",
        "deleteAll": "Удалить все",
        "deleteSelected": "Удалить выбранные",
        "select": "Выбрать",
        "unselect": "Отменить выбор",
        "unselectAll": "Снять все отметки",
        "selectAll": "Выбрать все",
        "save": "Сохранить",
        "cancelSelect": "Отменить выбор",
        "add": "Добавить",
        "addPlus": "+",
        "addToFavorites": "Добавить в избранное",
        "deleteFromFavorites": "Удалить из избранного",
        "search": "Поиск",
        "sort": "Сортировка",
        "sortAscending": "А-Я",
        "sortDescending": "Я-А",
        "sortAscendingSegment": "А-Я",
        "sortDescendingSegment": "Я-А",
        "contextActions": "...",
        "settings": "Настройки",
        "help": "Помощь",
        "language": "Язык",
        "fullVersion": "Полная весрия",
        "fullAccess": "Полный доступ",
        "restorePurchases": "Восстановить покупки",
        "aboutApp": "О приложении",
        "askQuestion": "Задать вопрос",
        "share": "Поделиться",
        "reset": "Сбросить",
        "menu": "Меню",
        "back": "Назад",
        "rules": "Правила",
        "rate": "Оценить",
        "feedback": "Обратная связь",
        "rateApp": "Оценить приложение",
        "reviewApp": "Оставить отзыв",
        "play": "Играть",
        "newgame": "Новая игра",
        "continue": "Продолжить",
        "words": "Слова",
        "ownWords": "Свои слова",
        "ownThemes": "Свои темы",
        "ownCategories": "Свои категории",
        "allCategories": "Все категории",
        "categories": "Категории",
        "themes": "Темы",
        "taskText": "выполняя задание:",
        "explainsTeam": "объясняет\nкоманда #",
        "explainsPlayer": "объясняет\nигроку",
        "extraTimeIsActivatedTitle": "Дополнительные 15 секунды активированы",
        "timeIsOver": "Время вышло",
        "hatIsEmpty": "В Шляпе пусто",
        "hatIsEmptyMessage": "но у вас осталось\nTIME секунд.\nпоэтому следующий\nраунд начинаете Вы\nи у Вас будет\nTIME секунд",
        "gotScoresText_0": " набрали:",
        "gotScoresText_1": " набрал:",
        "ownSectionDesc": "Своя категория",
        "editGameTypeAlertTitle": "Точно изменить тип игры?",
        "editGameTypeAlertMessage": "При изменении типа игры, текущая игра не сохранится",
        "players": "Игроки",
        "teams": "Команды",
        "sections": "Разделы",
        "blocks": "Блоки",
        "articles": "Статьи",
        "reports": "Расчеты",
        "summary": "Отчеты",
        "tests": "Тесты",
        "test": "Тест",
        "bilets": "Билеты",
        "answers": "Ответы",
        "questions": "Вопросы",
        "errors": "Ошибки",
        "scores": "Очки",
        "allThemes": "Все темы",
        "all": "Все",
        "own": "Свои",
        "favorites": "Избранные",
        "selected": "Выбранные",
        "allSections": "Все разделы",
        "favoriteCategories": "Избранные категории",
        "favoriteThemes": "Избранные темы",
        "favoriteWords": "Избранные слова",
        "favoriteSections": "Избранные разделы",
        "close": "Закрыть",
        "round": "Раунд",
        "pause": "Пауза",
        "modes": "Режимы",
        "resetResults": "Стереть результаты",
        "gameModes": "Режим игры",
        "gameTime": "Время игры",
        "teamGame": "Командная игра",
        "team": "Командная",
        "singleGame": "Одиночная игра",
        "single": "Одиночная",
        "rounds": "Раундов",
        "sound": "Звук",
        "sounds": "Звуки",
        "gameType": "Тип игры",
        "start": "Начать",
        "name": "Имя",
        "surname": "Фамилия",
        "phone": "Телефон",
        "info": "Информация",
        "email": "Email",
        "address": "Адрес",
        "word": "Слово",
        "title": "Название",
        "letter": "Буква",
        "symbol": "Символ",
        "new_name": "Новое имя",
        "new_surname": "Новая фамилия",
        "new_phone": "Новый телефон",
        "new_info": "Новая информация",
        "new_email": "Новый email",
        "new_word": "Новое слово",
        "new_title": "Новое название",
        "new_letter": "Новая буква",
        "new_symbol": "Новый символ",
         "place": "Место",
         "number": "Номер",
        "roundText": "РАУНД",
        "defaulfTask": "стоя на коленях",
        "whoGuessAlertTitle": "Кто угадал последнее слово?",
        "commonText": "общее",
        "pauseText": "Пауза",
        "alertLikeAppTitle": "Нравится наш Alias)?",
        "alertRatePleaseTitle": "Мы очень рады!)",
        "alertRatePleaseMessage": "Поможете нам маленьким отзывом?",
        "alertRatePleaseLater": "Позже",
        "alertClearResultsTitle": "Стереть результаты",
        "alertClearResultsMessage": "Точно стираем все результаты?",
        "alertEdit": "Изменить",
        "alertNewTeamTitle_0": "Новое название",
        "alertNewTeamTitle_1": "Новое имя",
        "alertNewTeamMessage_0": "Введите новое название команды",
        "alertNewTeamMessage_1": "Введите новое имя игрока",
        "alertDelete": "Удалить",
        "alertDeleteTeamMessage": "Точно удаляем команду?",
        "alertDeleteTeamMessage_0": "Точно удаляем команду?",
        "alertDeleteTeamMessage_1": "Точно удаляем игрока?",
        "alertDeleteTeamTitle_0": "Удаление команды",
        "alertDeleteTeamTitle_1": "Удаление игрока",
        "alertmax20TeamTitle_0": "В игре должно быть не более 20 команд",
        "alertMin2TeamTitle_0": "В игре должно быть не менее двух команд",
        "alertOtherTeamMessage_0": "Такая команда уже есть",
        "alert1to14CharactersMessage_0": "Название команды должно содержать от 1 до 14 символов",
        "alertmax20TeamTitle_1": "В игре должно быть не более 20 игроков",
        "alertMin2TeamTitle_1": "В игре должно быть не менее двух игроков",
         "alertOtherTeamTitle_0": "Введите другое название",
        "alertOtherTeamTitle_1": "Введите другое имя",
         "alertOtherTeamTitle": "Enter another name",
        "alertOtherTeamMessage_1": "Такая имя уже есть",
        "alert1to14CharactersMessage_1": "Имя игрока должно содержать от 1 до 14 символов",
        "playsLabelName": "играют",
        "startButtonName": "Начать",
        "VictoryScoreLabelName": "Очки для победы:",
        "roundTimeLabelName": "Время игры",
        "roundCountLabelName": "Всего раундов",
        "victoryScoresLabelName": "Очков для победы",
        "lastWordLabelName": "Последнее слово",
        "gameWithTaskLabelName": "Игра с заданиями",
        "minusPerMistakeLabelName": "Минус за пропуск",
        "soundsLabelName": "Звуки",
        "modesTitle": "НАСТРОЙКИ",
        "wordsTitle": "КАТЕГОРИИ",
        "playersTitle": "ИГРОКИ",
        "rulesTitle": "ПРАВИЛА",
        "resultTitle": "РЕЗУЛЬТАТ",
        "clearButtonName": "Сбросить результаты",
        "currentScoreLabelName": "ТЕКУЩИЙ СЧЕТ",
        "rateButtonName": "Оставить отзыв",
        "lastWordGameLabelName": "последнее слово",
        "nextButtonName": "Продолжить",
        "menuButtonName": "Меню",
        "ownWordsTitle": "СВОИ СЛОВА",
        "deletedWordsTitle": "УДАЛЕННЫЕ СЛОВА",
        "addOwnWordsTitle": "Добавьте больше слов",
        "addOwnWordsMessage": "Чтобы выбрать тему 'Свои слова', добавьте хотя бы 2 собственных слова. Чтобы добавить слова, нажмите '+' в правом верхнем углу экрана.",
        "addOwnWordsForThemeMessage": "Чтобы выбрать свою категорию, добавьте в нее хотя бы 2 слова. Чтобы добавить слова в категорию, нажмите кнопку '+' в этой категории.",
        "maxWordsTitle": "Вы можете добавить всего 300 своих слов",
        "maxWordsMessage": "Уже добавленные слова можно удалять. Для это проведите пальцем по слову справа налево",
        "addWordTitle": "Добавить слово",
        "addWordMessage": "Введите новое слово",
        "removeWordTitle": "Удаление всех слов",
        "removeWordMessage": "Точно удаляем все слова?",
        "totalWord": "Всего слов",
        "category": "Категория",
        "categoryWordsCount": "Слов: ",
        "removeOneWordTitle": "Удаление слова",
        "removeOneWordMessage": "Точно удаляем слово?",
        "wordExistsTitle": "Такое слово уже есть",
        "wordExistsMessage": "Введите другое слово",
        "longWordTitle": "Cлишком длинное слово",
        "longWordMessage": "Слово должно содержать от 1 до 30 символов",
        "incorrectWordTitle": "Некорректное слово",
        "incorrectWordMessage": "Слово не должно содержать следующие символы:  ;~`^@#$%№&*|\'/[](){}<>",
        "gameTypeCommand": "Командная",
        "gameTypeSingle": "Одиночная",
        "reviewAppTitle": "Ну как Вам?",
        "reviewAppMessage": "Понравилась наша игра?:)",
        "reviewAppWillReview": "Да! Поставлю Вам оценку :)",
        "reviewAppAlreadyReview": "Да, отзыв уже оставлен :)",
        "reviewAppNotDecide": "Пока не понятно...",
        "reviewAppGameSucks": "Нет, игра отстой :(",
        "reviewAppClose": "Закрыть",
        "allResultsLabelText": "В этой игре:",
        "reviewAlertTitle": "Hello!:)",
        "reviewAlertMessage": "Well, do you enjoy our game?:)",
        "reviewAlertLeaveReview": "Yes! I will rate it! :)",
        "reviewAlertAlreadyLeft": "Yes, my review has already been left :)",
        "reviewAlertNotDecided": "Haven't decided yet..."
    ],
    "en": [
        
        "notEnoughWordsAlertTitle": "Недостаточно слов для игры",
        "notEnoughWordsAlertMessage": "Вы выбрали категории, в которых суммарно слов меньше, чем задано в настройках игры. Сейчас в настройках выбрано SETTINGS_WORDS_COUNT слов в игре, а в категориях суммарно GAME_WORDS_COUNT слов. Чтобы начать новую игру, измените выбранные категории, либо поменяйте количество слов в настройках игры.",
        
        "resultsVCTitle": "Result",
        "sectionsVCTitle": "Categories",
        "settingsVCTitle": "Settings",
        "rulesVCTitle": "Rules",
        
        //ownwords
        "OwnwordTableViewCellTitle": "OwnwordTableViewCell",
        "ownwordsVCTitle": "Own words",
        "addOrEditOwnwordVCTitle": "Add new word",
        "alertAddOwnwordTitle": "Add new word",
        "alertAddOwnwordMessage": "Enter new word",
        "alertEditOwnwordTitle": "Edit word",
        "alertEditOwnwordMessage": "Enter new word. Old word: ",
        "alertMaxOwnwordsCountTitle": "Unable to add word",
        "alertMaxOwnwordsCountMessage": "Maximum words count: maximumCount",
        "alertMinOwnwordsCountTitle": "Unable to delete words",
        "alertMinOwnwordsCountMessage": "Minimum words count: minimumCount",
        "alertDeleteOwnwordTitle": "Delete word",
        "alertDeleteOwnwordMessage": "Are you sure you want to delete the word? This action cannot be undone",
        "alertDeleteSelectedOwnwordsTitle": "Delete selected words",
        "alertDeleteSelectedOwnwordsMessage": "Are you sure you want to delete selected words? This action cannot be undone",
        "alertDeleteAllOwnwordsTitle": "Delete all words",
        "alertDeleteAllOwnwordsMessage": "Are you sure you want to delete all words? This action cannot be undone",
        
        //categories
        "SectionTableViewCellTitle": "SectionTableViewCell",
        "sections2VCTitle": "sections2VC",
        "addOrEditSectionVCTitle": "Add new category",
        "alertAddSectionTitle": "Add new category",
        "alertAddSectionMessage": "Enter new category name",
        "alertEditSectionTitle": "Edit category",
        "alertEditSectionMessage": "Enter new category name. Old name: ",
        "alertMaxSectionsCountTitle": "Unable to add category",
        "alertMaxSectionsCountMessage": "Maximum categories count: maximumCount",
        "alertMinSectionsCountTitle": "Unable to delete categories",
        "alertMinSectionsCountMessage": "Minimum categories count: minimumCount",
        "alertDeleteSectionTitle": "Delete category",
        "alertDeleteSectionMessage": "Are you sure you want to delete the category? This action cannot be undone",
        "alertDeleteSelectedSectionsTitle": "Delete selected categories",
        "alertDeleteSelectedSectionsMessage": "Are you sure you want to delete selected categories? This action cannot be undone",
        "alertDeleteAllSectionsTitle": "Delete all categories",
        "alertDeleteAllSectionsMessage": "Are you sure you want to delete all categories? This action cannot be undone",
        
        //players
        "playersVCTitle": "Players",
        "alertAddPlayerTitle": "Add new player",
        "alertAddPlayerMessage": "Enter new player name",
        "alertEditPlayerTitle": "Edit player",
        "alertEditPlayerMessage": "Enter new player name. Old name: ",
        "alertMaxPlaayersCountTitle": "Unable to add players",
        "alertMaxPlayersCountMessage": "Maximum players count: maximumCount",
        "alertMinPlayersCountTitle": "Unable to delete players",
        "alertMinPlayersCountMessage": "Minimum players count: minimumCount",
        "alertDeletePlayerTitle": "Delete player",
        "alertDeleteSelectedPlayersTitle": "Delete selected players",
        "alertDeleteAllPlayersTitle": "Delete all players",
        "alertDeletePlayerMessage": "Are you sure you want to delete the player? This action cannot be undone",
        "alertDeleteSelectedPlayersMessage": "Are you sure you want to delete selected players? This action cannot be undone",
        "alertDeleteAllPlayersMessage": "Are you sure you want to delete all players? This action cannot be undone",
        "alertDeleteAllPlayersAdditionalMessage": ". Minimum players count: 2. Therefore, all players except the first 2 will be deleted.",
    
        "parentControl": "ASK YOUR PARENTS",
        "guessedAction": "Guessed",
        "notguessedAction": "Not guessed",
        "InsectCollectionViewCellTitle": "InsectCollectionViewCell",
        "insectsVCTitle": "insectsVC",
        "addOrEditInsectVCTitle": "Add new insect",
        "alertAddInsectTitle": "Add new insect",
        "alertAddInsectMessage": "Enter new insect name",
        "alertEditInsectTitle": "Edit insect",
        "alertEditInsectMessage": "Enter new insect name. Old name: ",
        "alertMaxInsectsCountTitle": "Unable to add insect",
        "alertMaxInsectsCountMessage": "Maximum insects count: maximumCount",
        "alertMinInsectsCountTitle": "Unable to delete insects",
        "alertMinInsectsCountMessage": "Minimum insects count: minimumCount",
        "alertDeleteInsectTitle": "Delete insect",
        "alertDeleteInsectMessage": "Are you sure you want to delete the insect? This action cannot be undone",
        "alertDeleteSelectedInsectsTitle": "Delete selected insects",
        "alertDeleteSelectedInsectsMessage": "Are you sure you want to delete selected insects? This action cannot be undone",
        "alertDeleteAllInsectsTitle": "Delete all insects",
        "alertDeleteAllInsectsMessage": "Are you sure you want to delete all insects? This action cannot be undone",
        // purcahses
        "restorePurchasesTitle": "Restore Purchases",
        "restorePurchasesMessage": "Purchases have been successfully restored",
        "completePurchasesTitle": "Purchase Full Version",
        "completePurchasesMessage": "Purchase has been completed successfully. Full version is opened",
        "completeManyPurchasesTitle": "Purchase",
        "completeManyPurchasesMessage": "Purchase has been completed successfully",
        "restoringMessage": "Restoring purchases is in progress",
        "loadingMessage": "Loading",
        "errorTitle": "Error occurred",
        "errorMessage": "The operation failed. Please check your Internet connection and try again.",
         //birds
         "all birds": "Все птицы",
         "own birds": "Мои птицы",
        "BirdTableViewCellTitle": "BirdTableViewCell",
        "birds2VCTitle": "birds2VC",
        "addOrEditBirdVCTitle": "Add new bird",
        "alertAddBirdTitle": "Add new bird",
        "alertAddBirdMessage": "Enter new bird name",
        "alertEditBirdTitle": "Edit bird",
        "alertEditBirdMessage": "Enter new bird name. Old name: ",
        "alertMaxBirdsCountTitle": "Unable to add bird",
        "alertMaxBirdsCountMessage": "Maximum birds count: maximumCount",
        "alertMinBirdsCountTitle": "Unable to delete birds",
        "alertMinBirdsCountMessage": "Minimum birds count: minimumCount",
        "alertDeleteBirdTitle": "Delete bird",
        "alertDeleteBirdMessage": "Are you sure you want to delete the bird? This action cannot be undone",
        "alertDeleteSelectedBirdsTitle": "Delete selected birds",
        "alertDeleteSelectedBirdsMessage": "Are you sure you want to delete selected birds? This action cannot be undone",
        "alertDeleteAllBirdsTitle": "Delete all birds",
        "alertDeleteAllBirdsMessage": "Are you sure you want to delete all birds? This action cannot be undone",
        
        
        
         "playersCountNameLabel": "Команд",
         "roundsCountNameLabel": "Раундов",
         "soundsOnNameLabel": "Звуки",
         "gameModesNameLabel": "Режимы",
         "playersButton": "Игроки",
         "playButton": "Играть",
         "titleLabel": "Текст лейбла",
         "item_1": "item_1",
         "item_2": "item_2",
         //names
         "namesVCTitle": "Имена",
         "alertAddNameTitle": "Добавить новое имя",
         "alertAddNameMessage": "Введите новое имя",
         "alertEditNameTitle": "Изменить имя",
         "alertEditNameMessage": "Введите новое имя. Старое имя: ",
         "alertMaxNamesCountTitle": "Нельзя добавить имя",
         "alertMaxNamesCountMessage": "Количество имен не должно быть больше maximumCount",
         "alertMinNamesCountTitle": "Нельзя удалить имя",
         "alertMinNamesCountMessage": "Количество имен не должно быть меньше minimumCount",
         "alertDeleteNameTitle": "Удалить имя",
         "alertDeleteSelectedNamesTitle": "Удалить выбранные имена",
         "alertDeleteAllNamesTitle": "Удалить все имена",
         "alertDeleteNameMessage": "Точно удаляем имя? Данное действие нельзя будет отменить",
         "alertDeleteSelectedNamesMessage": "Точно удаляем выбранные имена? Данное действие нельзя будет отменить",
         "alertDeleteAllNamesMessage": "Точно удаляем все имена? Данное действие нельзя будет отменить",
         //clients
         "clientsVCTitle": "Клиенты",
         "alertAddClientTitle": "Добавить нового клиента",
         "alertAddClientMessage": "Введите новое имя клиента",
         "alertEditClientTitle": "Изменить клиента",
         "alertEditClientMessage": "Введите новое имя клиента. Старое имя: ",
         "alertMaxClientsCountTitle": "Нельзя добавить клиента",
         "alertMaxClientsCountMessage": "Количество клиентов не должно быть больше maximumCount",
         "alertMinClientsCountTitle": "Нельзя удалить клиентов",
         "alertMinClientsCountMessage": "Количество клиентов не должно быть меньше minimumCount",
         "alertDeleteClientTitle": "Удалить клиента",
         "alertDeleteSelectedClientsTitle": "Удалить выбранных клиентов",
         "alertDeleteAllClientsTitle": "Удалить всех клиентов",
         "alertDeleteClientMessage": "Точно удаляем клиента? Данное действие нельзя будет отменить",
         "alertDeleteSelectedClientsMessage": "Точно удаляем выбранных клиентов? Данное действие нельзя будет отменить",
         "alertDeleteAllClientsMessage": "Точно удаляем всех клиентов? Данное действие нельзя будет отменить",
         //fruits
         "fruitsVCTitle": "Фрукты",
         "alertAddFruitTitle": "Добавление фрукта",
         "alertAddFruitMessage": "Введите новое название фрукта",
         "alertEditFruitTitle": "Изменение фрукта",
         "alertEditFruitMessage": "Введите новое название фрукта. Старое название: ",
         "alertMaxFruitsCountTitle": "Нельзя добавить фрукт",
         "alertMaxFruitsCountMessage": "Количество фруктов не должно быть больше maximumCount",
         "alertMinFruitsCountTitle": "Нельзя удалить фрукты",
         "alertMinFruitsCountMessage": "Количество фруктов не должно быть меньше minimumCount",
         //all
         "lettersVCTitle": "Буквы",
         "animalsVCTitle": "Животные",
        "ownTheme": "Own category",
         "allSections": "Все разделы",
        "lettersVCNavigationBarTitle": "lettersVC",
        "commandsTitle": "TEAMS",
        "gameTypeLabelLabelName": " game",
        "mailSubject": "Questions for the game",
        "mailMessage": "Write your question here",
        "newGameButtonName": "New game",
        "continueButtonName": "Continue",
        "newGameAlertTitle": "Do you want to begin a new game?",
        "newGameAlertMessage": "All the results will be deleted",
        "сancel": "Отмена",
        "yes": "Да",
        "no": "Нет",
        "ok": "OK",
        "edit": "Изменить",
        "delete": "Удалить",
        "deleteAll": "Удалить все",
        "deleteSelected": "Удалить выбранные",
        "select": "Выбрать",
        "unselect": "Отменить выбор",
        "unselectAll": "Снять все отметки",
        "selectAll": "Выбрать все",
        "save": "Сохранить",
        "cancelSelect": "Отменить выбор",
        "add": "Добавить",
        "addPlus": "+",
        "addToFavorites": "Добавить в избранное",
        "deleteFromFavorites": "Удалить из избранного",
        "search": "Поиск",
        "sort": "Сортировка",
        "sortAscending": "->",
        "sortDescending": "<-",
        "sortAscendingSegment": "А-Я",
        "sortDescendingSegment": "Я-А",
        "contextActions": "...",
        "settings": "Настройки",
        "help": "Помощь",
        "language": "Язык",
        "fullVersion": "Полная весрия",
        "fullAccess": "Полный доступ",
        "restorePurchases": "Восстановить покупки",
        "aboutApp": "О приложении",
        "askQuestion": "Задать вопрос",
        "share": "Поделиться",
        "reset": "Сбросить",
        "menu": "Меню",
        "back": "Назад",
        "rules": "Правила",
        "rate": "Оценить",
        "feedback": "Обратная связь",
        "rateApp": "Оценить приложение",
        "reviewApp": "Оставить отзыв",
        "play": "Играть",
        "newgame": "Новая игра",
        "continue": "Продолжить",
        "words": "Слова",
        "ownWords": "Свои слова",
        "ownThemes": "Свои темы",
        "ownCategories": "Свои категории",
        "allCategories": "Все категории",
        "allThemes": "Все темы",
        "favoriteCategories": "Избранные категории",
        "favoriteThemes": "Избранные темы",
        "favoriteWords": "Избранные слова",
        "favoriteSections": "Избранные разделы",
        "round": "Раунд",
        "pause": "Пауза",
        "categories": "Категории",
        "themes": "Темы",
        "modes": "Режимы",
        "players": "Игроки",
        "teams": "Команды",
        "taskText": "выполняя задание:",
        "explainsTeam": "объясняет\nкоманда #",
        "explainsPlayer": "объясняет\nигроку",
        "extraTimeIsActivatedTitle": "Дополнительные 15 секунды активированы",
        "timeIsOver": "Время вышло",
        "hatIsEmpty": "В шляпе пусто",
        "hatIsEmptyMessage": "но у вас осталось\nTIME секунд.\nпоэтому следующий\nраунд начинаете Вы\nи у Вас будет\nTIME секунд",
        "gotScoresText_0": " набрали:",
        "gotScoresText_1": " набрал:",
        "ownSectionDesc": "Своя категория",
        "editGameTypeAlertTitle": "Точно изменить тип игры?",
        "editGameTypeAlertMessage": "При изменении типа игры, текущая игра не сохранится",
         "sections": "Разделы",
         "blocks": "Блоки",
         "articles": "Статьи",
         "reports": "Расчеты",
         "summary": "Отчеты",
         "tests": "Тесты",
         "test": "Тест",
         "bilets": "Билеты",
         "answers": "Ответы",
         "questions": "Вопросы",
         "errors": "Ошибки",
         "scores": "Очки",
        "resetResults": "Стереть результаты",
        "gameModes": "Режим игры",
        "gameTime": "Время игры",
        "teamGame": "Командная игра",
        "team": "Командная",
        "singleGame": "Одиночная игра",
        "single": "Одиночная",
        "rounds": "Раундов",
        "sound": "Звук",
        "sounds": "Звуки",
        "gameType": "Тип игры",
        "start": "Начать",
        "name": "Имя",
        "surname": "Фамилия",
        "phone": "Телефон",
        "info": "Информация",
        "email": "Email",
        "address": "Адрес",
         "word": "Слово",
         "title": "Название",
         "letter": "Буква",
         "symbol": "Символ",
         "new_name": "Новое имя",
         "new_surname": "Новая фамилия",
         "new_phone": "Новый телефон",
         "new_info": "Новая информация",
         "new_email": "Новый email",
         "new_word": "Новое слово",
         "new_title": "Новое название",
         "new_letter": "Новая буква",
         "new_symbol": "Новый символ",
        "all": "Все",
        "own": "Свои",
        "favorites": "Избранные",
        "selected": "Выбранные",
        "close": "Закрыть",
        "place": "Место",
        "number": "Номер",
        "alertIncorrectSymbolsCountTitle": "Некорректное число символов",
        "alertIncorrectSymbolsCountMessage": "currentTitle должно содержать от minimumSymbolsCount до maximumSymbolsCount символов",
        "alertIncorrectNameTitle": "Некорректное currentTitle",
        "alertIncorrectNameMessage": "Такое currentTitle уже есть. Введите другое.",
        "alertIncorrectSymbolsTitle": "Некорректные символы",
        "alertIncorrectSymbolsMessage": "Нельзя использовать символы: incorrectSymblosString",
        "roundText": "ROUND",
        "defaulfTask": "kneeling",
        "whoGuessAlertTitle": "Who guessed the word?",
        "commonText": "common",
        "pauseText": "Pause",
        "alertLikeAppTitle": "Enjoy using Alias?",
        "alertRatePleaseTitle": "Hero!",
        "alertRatePleaseMessage": "Can you help us with a quick review?",
        "alertRatePleaseLater": "Later",
        "alertClearResultsTitle": "Reset results",
        "alertClearResultsMessage": "Are you sure you want to reset all results?",
        "alertNewTeamTitle_0": "New name",
        "alertNewTeamTitle_1": "New name",
        "alertNewTeamMessage_0": "Enter new team name",
        "alertNewTeamMessage_1": "Enter new player name",
        "alertDelete": "Delete",
         "alertEdit": "Изменить",
        "alertDeleteTeamTitle_0": "Delete team",
        "alertDeleteTeamTitle_1": "Delete player",
         "alertDeleteTeamMessage": "Точно удаляем команду?",
        "alertDeleteTeamMessage_0": "Are you sure you want to delete the team?",
        "alertDeleteTeamMessage_1": "Are you sure you want to delete the player?",
        "alertmax20TeamTitle_0": "You can add only 20 teams in the game.",
        "alertmax20TeamTitle_1": "You can add only 20 players in the game.",
        "alertMin2TeamTitle_0": "You must add at least 2 teams in the game.",
        "alertMin2TeamTitle_1": "You must add at least 2 players in the game.",
        "alertOtherTeamTitle": "Enter another name",
         "alertOtherTeamTitle_0": "Введите другое название",
         "alertOtherTeamTitle_1": "Введите другое имя",
        "alertOtherTeamMessage_0": "This team already exists",
        "alertOtherTeamMessage_1": "This player already exists",
        "alert1to14CharactersMessage_0": "Team name should contain from 1 to 14 characters",
        "alert1to14CharactersMessage_1": "Player name should contain from 1 to 14 characters",
        "playsLabelName": "play",
        "startButtonName": "Start",
        "VictoryScoreLabelName": "Victory scores:",
        "roundTimeLabelName": "Game time",
        "roundCountLabelName": "Rounds number",
        "victoryScoresLabelName": "Victory scores",
        "lastWordLabelName": "Last word",
        "gameWithTaskLabelName": "Game with tasks",
        "minusPerMistakeLabelName": "Minus per pass",
        "soundsLabelName": "Sounds",
        "modesTitle": "GAME MODES",
        "wordsTitle": "WORDS",
        "playersTitle": "PLAYERS",
        "rulesTitle": "RULES",
        "resultTitle": "RESULT",
        "clearButtonName": "Reset results",
        "currentScoreLabelName": "CURRENT SCORES",
        "rateButtonName": "Rate the app",
        "lastWordGameLabelName": "last word",
        "nextButtonName": "Next",
        "menuButtonName": "Menu",
        "ownWordsTitle": "OWN WORDS",
        "deletedWordsTitle": "DELETED WORDS",
        "addOwnWordsTitle": "Add more words",
        "addOwnWordsMessage": "To select 'Own words' theme, add at least 2 own words. To add your own words, press '+' in the top right corner.",
        "maxWordsTitle": "You can only add 300 of your own words",
        "maxWordsMessage": "Already added words can be deleted: swipe the word from right to left and press Delete",
        "addWordTitle": "Add word",
        "addWordMessage": "Enter a new word",
        "removeWordTitle": "Delete all words",
        "removeWordMessage": "Are you sure you want to delete all words?",
        "totalWord": "Total words",
        "removeOneWordTitle": "Delete word",
        "removeOneWordMessage": "Are you sure you want to delete the word?",
        "wordExistsTitle": "This word already exists",
        "wordExistsMessage": "Enter the other word",
        "longWordTitle": "Too long word",
        "longWordMessage": "The word must contain between 1 and 30 characters",
        "incorrectWordTitle": "Incorrect word",
        "incorrectWordMessage": "The word must not contain the following characters: ;~`^@#$%№&*|\'/[](){}<>",
        "gameTypeCommand": "Team",
        "gameTypeSingle": "Single",
        "reviewAppTitle": "Hello!",
        "reviewAppMessage": "Did you like our game? :)",
        "reviewAppWillReview": "Yes! I'll rate it :)",
        "reviewAppAlreadyReview": "Yes, I have already rated your app :)",
        "reviewAppNotDecide": "Not decided yet",
        "reviewAppGameSucks": "No, the game sucks :(",
        "reviewAppClose": "Close",
        "allResultsLabelText": "In this game:",
        "reviewAlertTitle": "Hello!:)",
        "reviewAlertMessage": "Well, do you enjoy our game?:)",
        "reviewAlertLeaveReview": "Yes! I will rate it! :)",
        "reviewAlertAlreadyLeft": "Yes, my review has already been left :)",
        "reviewAlertNotDecided": "Haven't decided yet..."
    ]
]

